### ISSUE TITLE
Método poderia retornar booleano somente

### ISSUE THREAD

**Issue by orlandosaraivajr** [antoniolpcan/AnimaPlace#1]
Este método está iniciando sessão e outras atividades que poderiam ficar sob responsabilidade de quem chama este método.

https://github.com/antoniolpcan/AnimaPlace/blob/03fe239a5fe8ec7652508be08a6c97c61bf35ace/Codagem/php/ClassBD.php#L40

**Comment by antoniolpcan** [comment]
Entendido, só tinha tentado dar uma economizada nas linhas de código, atualizarei quando for possível.
